trigger:
  branches:
    include:
      - staging

pool:
  vmImage: ubuntu-latest

variables:
  - group: landing-jokerlabs

steps:
  - task: vercel-deployment-task@3
    displayName: Deploy to Vercel
    inputs:
      vercelProjectId: 'prj_O8guUeA0Vy4UMsiWFdvbHUrLvGCc'
      vercelTeamId: 'team_MFN4wLjnUblGCD8qM9jGoWRn'
      vercelToken: $(PAT-vercel)
      production: true
      debug: true
      logs: true
